mutation linkCreate($input: LinkCreateInput!) {
  linkCreate(input: $input) {
    link {
      ...CreatedLink
    }
    error {
      code
      message
    }
  }
}

fragment CreatedLink on Link {
  id
  ulid
  originalUrl
}
