# Write your query or mutation here
query GetCurrentUser {
  me {
    user {
      ...CurrentUser
    }
  }
}

fragment CurrentUser on User {
  id
  name
  surname
  email
  createdAt
  updatedAt
  links {
    ...UserLinks
  }
}

fragment UserLinks on Link {
  id
  ulid
  originalUrl
  createdAt
  updatedAt
  deletedAt
}
